---
apiVersion: v1
kind: Service
metadata:
  name: my-app-load-balancer-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # Load Balancer listens on port 80
      targetPort: 8080 # Forwards traffic to port 8080 on the container
  type: LoadBalancer
