apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: jenkins-token
  annotations:
    kubernetes.io/service-account.name: jenkins
# "kubectl apply -f jenkins-secret.yml -n webapps"
# "kubectl describe secret jenkins-token -n webapps"
