- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update the APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker.io
      apt:
        name: docker.io
        state: present

    - name: Chmod Docker docker.sock
      ansible.builtin.file:
        dest: /var/run/docker.sock
        mode: 666
