- name: Run Nexus Container
  hosts: all
  become: yes
  tasks:
    - name: Pull the latest SonarQube Docker image
      docker_image:
        name: sonatype/nexus3
        source: pull
        tag: latest

    - name: Run Nexus3 docker on port 8081
      ansible.builtin.command: docker run -d -p 8081:8081 --name nexus sonatype/nexus3

    - name: Wait for Nexus to be fully up and running
      wait_for:
        port: 8081
        host: "{{ inventory_hostname }}"
        state: started
        timeout: 180

    - name: Get Nexus initial admin password
      command: docker exec nexus cat /nexus-data/admin.password
      register: nexus_password

    - name: Display Nexus initial admin password
      debug:
        msg: "Nexus initial admin password is {{ nexus_password.stdout }}"

    - name: Display Nexus URL
      debug:
        msg: "Nexus is running and accessible at http://{{ inventory_hostname }}:8081"
